name: "Podcast Generator"
author: "Shah"
description: "Generates a feed for a podcast from a YAML file"
run:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: Commiter's email
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: Commiter's name
    required: true
    default: ${{ github.actor }}